apiVersion: batch/v1
kind: Job
metadata:
  name: wa-hls4ml-it
  labels:
    jobgroup: wa-hls4ml-it
spec:
  template:
    spec:
      containers:
      - name: ubuntu
        image:  ubuntu
        command: ["sh", "-c", "echo 'Interactive Pod, waiting for login' && sleep infinity"]
        terminationMessagePolicy: FallbackToLogsOnError
        volumeMounts:
        - name: amd-xilinx-tools
          mountPath: /opt/Xilinx
        - name: wa-search-output
          mountPath: /results
        resources:
          limits:
            memory: 4Gi
            cpu: "3"
          requests:
            memory: 2Gi
            cpu: "2"
      nodeSelector:
        nautilus.io/disktype: nvme
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: topology.kubernetes.io/region
                    operator: In
                    values:
                      - us-west
                  - key: feature.node.kubernetes.io/pci-10de.present
                    operator: NotIn
                    values:
                      - "true"
      volumes:
      - name: amd-xilinx-tools
        persistentVolumeClaim:
          claimName: amd-xilinx-tools
      - name: wa-search-output
        persistentVolumeClaim:
          claimName: wa-search-output
      restartPolicy: Never
  backoffLimit: 5